In [16]:
jobs = {
 
"AI Engineer":
"""
Large language models, machine learning,
deep learning, neural networks,
generative AI, retrieval augmented generation,
AI agents, model deployment and MLOps.
""",
 
"Data Engineer":
"""
Cloud infrastructure, ETL pipelines,
data lakes, distributed systems,
SQL, NoSQL, Spark, Airflow,
data architecture and scalability.
""",
 
"Business Intelligence Analyst":
"""
Dashboard design, KPIs,
Tableau, Power BI,
business reporting,
decision support and storytelling.
""",
 
"Sustainability Analyst":
"""
ESG reporting,
environmental monitoring,
sustainability metrics,
climate risk assessment
and environmental policy analysis.
""",
 
"Supply Chain Analyst":
"""
Demand forecasting,
inventory optimization,
transportation planning,
operations research,
logistics analytics and procurement.
""",
 
"Biomedical AI Specialist":
"""
Medical imaging,
diagnostic systems,
computer vision,
healthcare analytics,
deep learning and radiology.
"""
}
 

applicants = {
 
"A1":
"""
I enjoy building conversational AI systems,
working with transformers and deploying
machine learning models.
""",
 
"A2":
"""
I have experience in cloud computing,
data warehousing and designing scalable
data infrastructures.
""",
 
"A3":
"""
I enjoy analyzing climate indicators,
environmental risks and sustainability reporting.
""",
 
"A4":
"""
I like creating dashboards and translating
complex business information into visual stories.
""",
 
"A5":
"""
I am interested in medical imaging,
computer vision and healthcare applications.
"""
}

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [18]:
vectorizer = CountVectorizer()
bow_matrix=vectorizer.fit_transform(applicants.values())
features_names=vectorizer.get_feature_names_out()

In [19]:
import pandas as pd
bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    index=applicants.keys(),
    columns=features_names
)
bow_values=bow_matrix.toarray()
# Display result
print("Vocabulary:")
print(features_names)

print("\nBag of Words Matrix:")
print(bow_df)

Vocabulary:
['ai' 'am' 'analyzing' 'and' 'applications' 'building' 'business'
 'climate' 'cloud' 'complex' 'computer' 'computing' 'conversational'
 'creating' 'dashboards' 'data' 'deploying' 'designing' 'enjoy'
 'environmental' 'experience' 'have' 'healthcare' 'imaging' 'in'
 'indicators' 'information' 'infrastructures' 'interested' 'into'
 'learning' 'like' 'machine' 'medical' 'models' 'reporting' 'risks'
 'scalable' 'stories' 'sustainability' 'systems' 'transformers'
 'translating' 'vision' 'visual' 'warehousing' 'with' 'working']

Bag of Words Matrix:
    ai  am  analyzing  and  applications  building  business  climate  cloud  \
A1   1   0          0    1             0         1         0        0      0
A2   0   0          0    1             0         0         0        0      1
A3   0   0          1    1             0         0         0        1      0
A4   0   0          0    1             0         0         1        0      0
A5   0   1          0    1             1         0         0        0      0

    complex  ...  stories  sustainability  systems  transformers  translating  \
A1        0  ...        0               0        1             1            0
A2        0  ...        0               0        0             0            0
A3        0  ...        0               1        0             0            0
A4        1  ...        1               0        0             0            1
A5        0  ...        0               0        0             0            0

    vision  visual  warehousing  with  working
A1       0       0            0     1        1
A2       0       0            1     0        0
A3       0       0            0     0        0
A4       0       1            0     0        0
A5       1       0            0     0        0

[5 rows x 48 columns]

In [20]:
import numpy as np
vectorizers = TfidfVectorizer()
X=vectorizers.fit_transform(applicants.values())
words=vectorizers.get_feature_names_out()
tfidf_values=np.sum(X.toarray(),axis=0)
print(tfidf_values)
Z=pd.DataFrame(X.toarray(),index=applicants.keys(),columns=vectorizers.get_feature_names_out())
Z

[0.29015418 0.33561633 0.35628107 0.74973843 0.33561633 0.29015418
 0.31269768 0.35628107 0.27866103 0.31269768 0.33561633 0.27866103
 0.29015418 0.31269768 0.31269768 0.55732206 0.29015418 0.27866103
 0.52153988 0.35628107 0.27866103 0.27866103 0.33561633 0.33561633
 0.4955951  0.35628107 0.31269768 0.27866103 0.33561633 0.31269768
 0.29015418 0.31269768 0.29015418 0.33561633 0.29015418 0.35628107
 0.35628107 0.27866103 0.31269768 0.35628107 0.29015418 0.29015418
 0.31269768 0.33561633 0.31269768 0.27866103 0.29015418 0.29015418]

,ai,am,analyzing,and,applications,building,business,climate,cloud,complex,...,stories,sustainability,systems,transformers,translating,vision,visual,warehousing,with,working
A1,0.290154,0.000000,0.000000,0.138260,0.000000,0.290154,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.290154,0.290154,0.000000,0.000000,0.000000,0.000000,0.290154,0.290154
A2,0.000000,0.000000,0.000000,0.132783,0.000000,0.000000,0.000000,0.000000,0.278661,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.278661,0.000000,0.000000
A3,0.000000,0.000000,0.356281,0.169770,0.000000,0.000000,0.000000,0.356281,0.000000,0.000000,...,0.000000,0.356281,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
A4,0.000000,0.000000,0.000000,0.149002,0.000000,0.000000,0.312698,0.000000,0.000000,0.312698,...,0.312698,0.000000,0.000000,0.000000,0.312698,0.000000,0.312698,0.000000,0.000000,0.000000
A5,0.000000,0.335616,0.000000,0.159923,0.335616,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.335616,0.000000,0.000000,0.000000,0.000000

In [21]:
from sklearn.metrics.pairwise import cosine_similarity


score_bow = cosine_similarity(bow_values)
score_tfidf= cosine_similarity(X.toarray())

In [22]:
df_score_bow=pd.DataFrame(
    score_bow,
    index=applicants.keys(),
    columns=applicants.keys()
    )

df_score_tfidf=pd.DataFrame(
    score_tfidf,
    index=applicants.keys(),
    columns=applicants.keys()
    )

In [23]:
df_score_bow

          A1        A2        A3        A4        A5
A1  1.000000  0.074125  0.184900  0.083624  0.087706
A2  0.074125  1.000000  0.089087  0.080582  0.169031
A3  0.184900  0.089087  1.000000  0.100504  0.105409
A4  0.083624  0.080582  0.100504  1.000000  0.095346
A5  0.087706  0.169031  0.105409  0.095346  1.000000

In [ ]:
df_score_tfidf

          A1        A2        A3        A4        A5
A1  1.000000  0.018359  0.090762  0.020601  0.022111
A2  0.018359  1.000000  0.022543  0.019785  0.082111
A3  0.090762  0.022543  1.000000  0.025296  0.027150
A4  0.020601  0.019785  0.025296  1.000000  0.023829
A5  0.022111  0.082111  0.027150  0.023829  1.000000

# TF-IDF will be better 
### we can see a long range spread of numbers that in turn makes each applicant different from each other